### PR TITLE
Simplify distribution, migrate maps to .tmx format, correct BMFont file extension, support use as a library

### PR DESCRIPTION
**Pull request by Platonymous**

### CODE REVIEW

**Comment by Pathoschild** [comment]
Thanks for the pull request!

I'd rather avoid interactive wizard-style questions, since it's meant to be run quickly/repeatedly/automateably. It doesn't necessarily need to be configurable either since it's not meant to be a general-purpose unpacker; if the `.tmx` support works well, I'd be fine just dropping `.tbin` support since I prefer TMX anyway.

**Comment by Platonymous** [comment]
I checked the tmx exports and the all looked like they should. I don't see a good reason to keep tbin around either. I removed the choice again.

**Comment by Pathoschild** [comment]
@Platonymous When Tiled writes CSV tiles for a `.tmx` map, it breaks each row of tiles onto its own line. So if you have a 4x4 map, the data would be formatted like this:
```xml
<layer id="1" name="Back" width="80" height="75">
  <data encoding="csv">
0,0,0,0,
0,5,5,0,
0,5,5,0,
0,0,0,0
  </data>
</layer>
```

TMXTile puts them all on a single line like this instead:
```xml
<layer id="1" name="Back" width="80" height="75">
  <data encoding="csv">0,0,0,0,0,5,5,0,0,5,5,0,0,0,0,0</data>
</layer>
```

Could you change TMXTile to match the Tiled behavior?

**Comment by Platonymous** [comment]
I changed the extension for the BMFont files from xml to fnt, as that's what BMFont (https://www.angelcode.com/products/bmfont/) actually uses.

**Comment by Platonymous** [comment]
I changed the export format to csv, and TMXTile 1.5.1 has the layer-width dependend line breaks.

**Comment by Pathoschild** [comment]
This PR has too many unrelated changes now, some of which could be merged now if they weren't part of a combined PR. Can you submit separate PRs so they can be reviewed/discussed/merged separately?

Suggested split:

* Add assembly probe path to simplify distribution.
* Add support for use as a library.
* Correct BMFont file extension.
* Migrate maps to TMX format.

**Comment by Platonymous** [comment]
All seperated. Closing this.

**Pull request closed without merging**
