### PR TITLE
Prep for using StardewXnbHack as a library

### PR DESCRIPTION
**Pull request by Platonymous**
Makes internal framework public and removes platform dependent code.

### CODE REVIEW

**Comment by Pathoschild** [comment]
I'd rather not expose the internals like this; anything using the library would need to reimplement the main logic, and we couldn't change the implementation without breaking consumers.

Would a higher-level API like this work for you?

```cs
// build instance
var unpacker = new StardewXnbHack(
   game: Game1.game1, // or StardewXnbHack.CreateTemporaryGame()
   logger: _ => new ModProgressReporter() // optionally replace logging / progress tracking
);

// unpack
unpacker.Unpack(
   fromPath: Path.Combine(Constants.ExecutionPath, Game1.content.RootDirectory),
   toPath: Path.Combine(Constants.ExecutionPath, "Content (unpacked)"),
);
````

**Comment by Platonymous** [comment]
That would work.

**Comment by Pathoschild** [comment]
@Platonymous I added a simpler API which wraps the run logic (all arguments optional):
```cs
StardewXnbHack.Program.Run(
    game: Game1.game1,
    gamePath: Constants.ExecutionPath,
    getLogger: (context, defaultLogger) => new ModProgressLogger(context)
);
```

I ran it from an in-game mod which seemed to work fine:
> 

Let me know whether that works for you.

**Comment by Platonymous** [comment]
On windows it does, but this still has the plattform dependend compile for the glyphs in the spritefont writer, so would this not require different versions for different plattforms?

**Comment by Pathoschild** [comment]
@Platonymous Fixed that in `develop`. Thanks for the PR!

**Pull request closed without merging**
