### PR TITLE
Make tmx the export format for maps

### PR DESCRIPTION
**Pull request by Platonymous**
Uses TMXTile to make tmx the export format for maps.

### CODE REVIEW

**Comment by Pathoschild** [comment]
Thanks! I'd like to get the exported `.tmx` format as close to Tiled's format as feasible before merging this.

I unpacked `Maps/town` with these changes (left), then opened & resaved it in Tiled (right):
> image

Some of the changes might be too much work to fix, but others might be easier. For example:

* Tiled sorts map properties by name, but TMXTile doesn't.
* TMXTile doesn't set objectgroup and object IDs.
* TMXTile adds some extra fields that Tiled omits (like `<object rotation="0">`, `<property type="string">`, and `<objectgroup visible="false" locked="false">`).
* TMXTile adds XML schemas, but Tiled doesn't.

**Comment by Platonymous** [comment]
The last commit relates to TMXTile 1.5.2, as that has some format adjustments added.

**Comment by Pathoschild** [comment]
Thanks, the new format is almost perfect! Just a few differences left:

* TMXTile doesn't sort tiles by ID.
* TMXTile adds this extra line for each layer (left is TMXTile, right is Tiled):
  
* TMXTile is missing the `compressionlevel="0"` field on `map`.
* We should probably match Tiled's `version="1.4"` field on `map` too.

**Comment by Platonymous** [comment]
TMXTile 1.5.5 addresses all of those and from first glance seem to produce identical results now.

**Comment by Pathoschild** [comment]
Thanks! I submitted Platonymous/TMXTile#4 to fix a performance issue in the latest versions, but otherwise it looks great so far.

**Review by Pathoschild — APPROVED** [review]

**Comment by Pathoschild** [comment]
Thanks! Merged into `develop` for the upcoming StardewXnbHack 1.0.

**Pull request merged**
